sudo: required
services:
  - docker

before_install:
  - docker build -t sameureka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sameureka/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker-udemy'
  env: 'DockerUdemy-env'
  bucket_name: 'elasticbeanstalk-us-west-1-465048818173'
  bucket_path: 'docker'
  on:
    branch: 'master'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
